<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-09T12:14:33 IST" name="Sanity Test Suite" finished-at="2021-05-09T12:14:59 IST" duration-ms="26236">
    <groups>
    </groups>
    <test started-at="2021-05-09T12:14:33 IST" name="Cowin App Sanity Test Cases" finished-at="2021-05-09T12:14:59 IST" duration-ms="26236">
      <class name="testcases.ValidLoginPageTest">
        <test-method is-config="true" signature="setUpDBConnection()[pri:0, instance:testcases.ValidLoginPageTest@70887727]" started-at="2021-05-09T12:14:33 IST" name="setUpDBConnection" finished-at="2021-05-09T12:14:34 IST" duration-ms="922" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpDBConnection -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.ValidLoginPageTest@70887727]" started-at="2021-05-09T12:14:34 IST" name="setUp" finished-at="2021-05-09T12:14:40 IST" duration-ms="5611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTest()[pri:2, instance:testcases.ValidLoginPageTest@70887727]" started-at="2021-05-09T12:14:40 IST" name="loginTest" description="Verifying login and logout" finished-at="2021-05-09T12:14:52 IST" duration-ms="12622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.ValidLoginPageTest@70887727]" started-at="2021-05-09T12:14:53 IST" name="tearDown" finished-at="2021-05-09T12:14:53 IST" duration-ms="651" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testcases.ValidLoginPageTest@70887727]" started-at="2021-05-09T12:14:53 IST" name="setUp" finished-at="2021-05-09T12:14:57 IST" duration-ms="3884" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyTitle()[pri:0, instance:testcases.ValidLoginPageTest@70887727]" started-at="2021-05-09T12:14:57 IST" name="verifyTitle" description="Verifying login title" finished-at="2021-05-09T12:14:57 IST" duration-ms="20" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Co-WIN Applic11ation] but found [Co-WIN Application]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Co-WIN Applic11ation] but found [Co-WIN Application]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcases.ValidLoginPageTest.verifyTitle(ValidLoginPageTest.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.ValidLoginPageTest@70887727]" started-at="2021-05-09T12:14:58 IST" name="tearDown" finished-at="2021-05-09T12:14:59 IST" duration-ms="1114" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.ValidLoginPageTest -->
    </test> <!-- Cowin App Sanity Test Cases -->
  </suite> <!-- Sanity Test Suite -->
  <suite started-at="2021-05-09T12:15:00 IST" name="Cowin Test Automation Test Suite" finished-at="2021-05-09T12:15:00 IST" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- Cowin Test Automation Test Suite -->
</testng-results>
